# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with: 
        name: release
        path: Legend/bin/Debug/net6/Legend.dll
    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        prerelease: true
        tag_name: ${{ steps.build.outputs.TAG_NAME }}
        name: Release ${{ steps.build.outputs.TAG_NAME }}
        files: Legend/bin/Debug/net6/Legend.dll
